### PR TITLE
derive: `SchemaRead` ref constraints

### LINKED ISSUE #145: Reference to zero-copy type triggers IntEncoding error related to ZeroCopy trait
```rust
#[derive(SchemaWrite, SchemaRead)]
#[wincode(internal)]
enum ZeroRef<'a> {
    Unit,
    Ref(&'a StructZeroCopy),
}
```

generates
```
error[E0277]: the trait bound `<WincodeConfig as config::ConfigCore>::IntEncoding: config::serde::ZeroCopy<WincodeConfig>` is not satisfied
    --> wincode/src/schema/mod.rs:1405:13
     |
1405 |         Ref(&'a StructZeroCopy),
     |             ^^^^^^^^^^^^^^^^^^ the trait `config::serde::ZeroCopy<WincodeConfig>` is not implemented for `<WincodeConfig as config::ConfigCore>::IntEncoding`
     |
note: required for `u128` to implement `config::serde::ZeroCopy<WincodeConfig>`
    --> wincode/src/schema/impls.rs:53:44
     |
53   |                 unsafe impl<C: ConfigCore> ZeroCopy<C> for $type where C::IntEncoding: ZeroCopy<C> {}
     |                                            ^^^^^^^^^^^                                 ----------- unsatisfied trait bound introduced here
...
105  | impl_int_config_dependent!(u16, u32, u64, u128, i16, i32, i64, i128);
     | ------------------------------------------^^^^---------------------- in this macro invocation
     = note: 1 redundant requirement hidden
     = note: required for `StructZeroCopy` to implement `config::serde::ZeroCopy<WincodeConfig>`
note: required for `&'de StructZeroCopy` to implement `schema::SchemaRead<'de, WincodeConfig>`
    --> wincode/src/schema/impls.rs:1455:36
     |
1455 | unsafe impl<'de, T, C: ConfigCore> SchemaRead<'de, C> for &'de T
     |                                    ^^^^^^^^^^^^^^^^^^     ^^^^^^
1456 | where
1457 |     T: SchemaRead<'de, C> + ZeroCopy<C>,
     |                             ----------- unsatisfied trait bound introduced here
     = note: this error originates in the macro `impl_int_config_dependent` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the leading `&`-reference
     |
1405 -         Ref(&'a StructZeroCopy),
1405 +         Ref(StructZeroCopy),
     |
help: consider further restricting the associated type
     |
1403 |     enum ZeroRef<'a> where <WincodeConfig as config::ConfigCore>::IntEncoding: config::serde::ZeroCopy<WincodeConfig> {
     |                      ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<WincodeConfig as config::ConfigCore>::IntEncoding: config::serde::ZeroCopy<WincodeConfig>` is not satisfied
    --> wincode/src/schema/mod.rs:1405:13
     |
1405 |         Ref(&'a StructZeroCopy),
     |             ^^^^^^^^^^^^^^^^^^ the trait `config::serde::ZeroCopy<WincodeConfig>` is not implemented for `<WincodeConfig as config::ConfigCore>::IntEncoding`
     |
note: required for `u128` to implement `config::serde::ZeroCopy<WincodeConfig>`

```

### PR DESCRIPTION
**Pull request by cpubot**
Prior to the 0.3.0 release, `ZeroCopy` was implemented unconditionally for integer types on little endian targets. This meant that taking references to integer types or zero-copy structs containing integer types in a `SchemaRead` derived struct/enum trivially type-checked.

E.g.,
```rs
#[derive(SchemaWrite, SchemaRead)]
#[wincode(internal)]
enum ZeroRef<'a> {
    Unit,
    Ref(&'a StructZeroCopy),
}
```
Where `StructZeroCopy` contains integer types, (among other byte array types).

Since 0.3.0, `ZeroCopy` depends on the `Config` used for deserialization. And, more specifically, `SchemaRead` is only implemented on references `&T` where `T: ZeroCopy<Config>`. 
https://github.com/anza-xyz/wincode/blob/cc7074c2990615c335fe6580cfb7a36a50ad7a2f/wincode/src/schema/impls.rs#L1455-L1457

As such, the above example does not trivially type-check unless additional constraints are added to the `SchemaRead` implementation. In particular, the following constraint is needed:
```rs
where &'de StructZeroCopy: SchemaRead<'de, Config>
```

More generally, types containing references deriving `SchemaRead` must ensure that those references implement `SchemaRead<'de, Config>`. It would also be sufficient to constrain `T: ZeroCopy` (as it implies the former), but this is more complicated from a code generation perspective, specifically for types with generic lifetimes.

This PR implements a straight-forward solution. It iterates over fields whose types contain any lifetimes, and adds additional constraints to the where-clause that require those types to implement `SchemaRead<'de, Config>`.

Closes #145

### CODE REVIEW

File: wincode/src/schema/mod.rs [hunk 1]
```diff
@@ -3181,53 +3225,47 @@ mod tests {
     ///
     /// Implements [`Deref`] and [`DerefMut`] for `[u8]` such that it
     /// acts like a typical byte buffer, but aligned for `T`.
-    struct BufAligned<T> {
-        buf: Box<[T]>,
+    struct BufAligned {
+        buf: *mut u8,
+        layout: Layout,
```
Comment (kskalski) [inline wincode/src/schema/mod.rs:3230]: are those changes related to this PR?

Comment (cpubot) [reply wincode/src/schema/mod.rs:3230]: Yes, otherwise we can't test the enum impl because of the way the current serialize_aligned function is set up
